stages:
  - test
  - build

test:
  stage: test
  image: python:3.12
  before_script:
    - apt-get update
    - apt-get install -y gdal-bin libgdal-dev
  script:
    - pip install -r TaxiTracker/requirements.txt
    - cd TaxiTracker
    - python manage.py test

build:
  stage: build
  image: docker:latest
  script:
    - docker version
    - docker build -t taxitracker .