stages:
  - test
  - build

test:
  stage: test
  image: python:3.12

  script:
    - echo "Tests skipped temporarily"


  services:
    - name: postgis/postgis:16-3.4
      alias: postgres

  variables:
    SECRET_KEY: "ci-secret-key"
    DATABASE_NAME: test_taxitracker
    DATABASE_USERNAME: postgres
    DATABASE_PASSWORD: postgres
    DATABASE_PORT: 5432
    DATABASE_HOST: postgres

  before_script:
    - apt-get update
    - apt-get install -y gdal-bin libgdal-dev
    - pip install -r TaxiTracker/requirements.txt


build:
  stage: build
  image: docker:latest

  services:
    - docker:dind

  variables:
    DOCKER_TLS_CERTDIR: ""

  script:
    - docker version
    - docker build -t taxitracker ./TaxiTracker/TaxiTracker