stages:
  - test
  - build

test:
  stage: test
  image: python:3.12
  script:
    - pwd
    - ls -la
    - find . -name manage.py
    - pip install -r TaxiTracker/requirements.txt
    - cd TaxiTracker
    - python manage.py test

build:
  stage: build
  image: docker:latest
  script:
    - docker version
    - docker build -t taxitracker .