# Generated by Django 5.2.5 on 2025-08-24 13:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('car_class', models.CharField(max_length=2)),
                ('fuel_tank_capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)])),
                ('maximum_load_kg', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999)])),
                ('country_of_origin', models.CharField(max_length=100)),
                ('number_of_passengers', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
            ],
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('salary', models.IntegerField(validators=[django.core.validators.MaxValueValidator(250000)])),
                ('enterprise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='vehicles.enterprise')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_date', models.DateField()),
                ('odometer', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000000)])),
                ('price', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10000000)])),
                ('color', models.CharField(max_length=100)),
                ('plate_number', models.CharField(blank=True, max_length=9)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='vehicles.brand')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='vehicles.driver')),
                ('enterprise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='vehicles.enterprise')),
            ],
        ),
    ]
