# Generated by Django 4.2.11 on 2025-08-16 18:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_date', models.DateField()),
                ('odometer', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000000)])),
                ('price', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000000)])),
                ('country_of_origin', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
            ],
        ),
    ]
