# Generated by Django 4.2.11 on 2025-08-16 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='model_name',
            new_name='color',
        ),
    ]
