# Generated by Django 5.2.5 on 2026-01-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="car_purchase_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
