# Generated by Django 5.2.5 on 2026-01-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0002_vehicle_car_purchase_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="enterprise",
            name="timezone",
            field=models.CharField(
                choices=[
                    ("UTC", "UTC±00:00 — Coordinated Universal Time"),
                    ("Europe/London", "UTC±00:00 — London"),
                    ("Europe/Paris", "UTC+01:00 — Paris"),
                    ("Europe/Berlin", "UTC+01:00 — Berlin"),
                    ("Europe/Moscow", "UTC+03:00 — Moscow"),
                    ("Asia/Dubai", "UTC+04:00 — Dubai"),
                    ("Asia/Almaty", "UTC+06:00 — Almaty"),
                    ("Asia/Tashkent", "UTC+05:00 — Tashkent"),
                    ("Asia/Shanghai", "UTC+08:00 — Shanghai"),
                    ("Asia/Tokyo", "UTC+09:00 — Tokyo"),
                    ("America/New_York", "UTC−05:00 — New York"),
                    ("America/Chicago", "UTC−06:00 — Chicago"),
                    ("America/Denver", "UTC−07:00 — Denver"),
                    ("America/Los_Angeles", "UTC−08:00 — Los Angeles"),
                ],
                default="UTC",
                max_length=50,
            ),
        ),
    ]
