# Generated by Django 4.2.11 on 2025-08-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_rename_model_name_vehicle_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(default='Not specified', max_length=9),
        ),
    ]
