# Generated by Django 5.2.5 on 2025-08-24 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_alter_vehicle_driver_vehicledriver_vehicle_drivers'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vehicledriver',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='drivers',
            field=models.ManyToManyField(related_name='vehicles', through='vehicles.VehicleDriver', to='vehicles.driver'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.driver'),
        ),
        migrations.AlterField(
            model_name='vehicledriver',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.driver'),
        ),
        migrations.AlterField(
            model_name='vehicledriver',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vehicledriver',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle'),
        ),
    ]
