# Generated by Django 5.2.5 on 2026-02-01 06:58

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0004_alter_enterprise_timezone"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleTrackPint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "point",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["vehicle", "timestamp"],
                        name="vehicles_ve_vehicle_af16d9_idx",
                    )
                ],
            },
        ),
    ]
