# Generated by Django 5.2.5 on 2025-08-24 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_alter_vehicledriver_unique_together_vehicle_drivers_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vehicledriver',
            unique_together={('vehicle', 'driver')},
        ),
    ]
