# Generated by Django 4.2.11 on 2025-08-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_alter_vehicle_plate_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(default='_', max_length=10),
        ),
    ]
