# Generated by Django 5.2.5 on 2025-08-28 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_alter_vehicledriver_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='active_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_drivers', to='vehicles.vehicle'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vehicledriver',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_drivers', to='vehicles.vehicle'),
        ),
    ]
