# Generated by Django 5.2.5 on 2026-02-01 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0005_vehicletrackpint"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="VehicleTrackPint",
            new_name="VehicleTrackPoint",
        ),
        migrations.RenameIndex(
            model_name="vehicletrackpoint",
            new_name="vehicles_ve_vehicle_82fc68_idx",
            old_name="vehicles_ve_vehicle_af16d9_idx",
        ),
    ]
