# Generated by Django 5.2.5 on 2025-08-29 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_driver_active_vehicle_alter_driver_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledriver',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_drivers', to='vehicles.driver'),
        ),
    ]
