# Generated by Django 5.2.5 on 2026-02-12 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0006_rename_vehicletrackpint_vehicletrackpoint_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleTrip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_timestamp", models.DateTimeField(db_index=True)),
                ("end_timestamp", models.DateTimeField(db_index=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["vehicle", "start_timestamp", "end_timestamp"],
                        name="vehicles_ve_vehicle_6dd9a2_idx",
                    )
                ],
            },
        ),
    ]
