# Generated by Django 5.2.5 on 2026-02-14 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0007_vehicletrip"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicletrackpoint",
            name="trip",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="points",
                to="vehicles.vehicletrip",
            ),
        ),
    ]
