# Generated by Django 5.2.5 on 2026-02-14 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0008_vehicletrackpoint_trip"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vehicletrackpoint",
            old_name="trip",
            new_name="trip_id",
        ),
    ]
