# Generated by Django 4.2.11 on 2025-08-17 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0008_alter_vehicle_plate_number'),
    ]

    operations = [
    ]
