# Generated by Django 5.2.5 on 2026-02-15 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0009_rename_trip_vehicletrackpoint_trip_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicletrackpoint",
            name="trip_id",
        ),
    ]
