# Generated by Django 5.2.5 on 2025-09-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0009_manager_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='enterprise',
        ),
        migrations.AddField(
            model_name='manager',
            name='enterprises',
            field=models.ManyToManyField(blank=True, related_name='managers', to='vehicles.enterprise'),
        ),
    ]
