# Generated by Django 4.2.11 on 2025-08-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0010_brand_alter_vehicle_plate_number_alter_vehicle_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='country_of_origin',
        ),
        migrations.AddField(
            model_name='brand',
            name='country_of_origin',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
