# Generated by Django 5.2.5 on 2026-03-11 18:28

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0010_remove_vehicletrackpoint_trip_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_name", models.CharField(max_length=100)),
                ("report_start_date", models.DateField()),
                ("report_end_date", models.DateField()),
                ("report_period", models.DurationField(default=datetime.timedelta)),
                ("report_result", models.JSONField(blank=True, default=list)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vehicles.vehicle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DailyReport",
            fields=[
                (
                    "vehiclereport_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="vehicles.vehiclereport",
                    ),
                ),
            ],
            bases=("vehicles.vehiclereport",),
        ),
        migrations.CreateModel(
            name="MonthlyReport",
            fields=[
                (
                    "vehiclereport_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="vehicles.vehiclereport",
                    ),
                ),
            ],
            bases=("vehicles.vehiclereport",),
        ),
        migrations.CreateModel(
            name="RandomReport",
            fields=[
                (
                    "vehiclereport_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="vehicles.vehiclereport",
                    ),
                ),
            ],
            bases=("vehicles.vehiclereport",),
        ),
        migrations.CreateModel(
            name="WeeklyReport",
            fields=[
                (
                    "vehiclereport_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="vehicles.vehiclereport",
                    ),
                ),
            ],
            bases=("vehicles.vehiclereport",),
        ),
        migrations.CreateModel(
            name="ResultPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("duration", models.DurationField(default=datetime.timedelta)),
                ("value", models.FloatField()),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="vehicles.vehiclereport",
                    ),
                ),
            ],
            options={
                "ordering": ["duration"],
            },
        ),
    ]
