# Generated by Django 5.2.5 on 2026-04-01 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "vehicles",
            "0011_vehiclereport_dailyreport_monthlyreport_randomreport_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telegram_id", models.BigIntegerField(unique=True)),
                (
                    "manager",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vehicles.manager",
                    ),
                ),
            ],
        ),
    ]
