# Generated by Django 5.2.5 on 2026-04-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_bot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramprofile",
            name="first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="telegramprofile",
            name="is_bot",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="telegramprofile",
            name="language_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="telegramprofile",
            name="last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="telegramprofile",
            name="username",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
