# Generated by Django 5.2.5 on 2026-04-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "telegram_bot",
            "0002_telegramprofile_first_name_telegramprofile_is_bot_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramprofile",
            name="last_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
