[uwsgi]

# Папка проекта (где manage.py)
chdir = /Users/vladimirkorneev/Desktop/TaxiTracker/TaxiTracker/TaxiTracker

# Django WSGI модуль (важно: имя проекта = TaxiTracker)
module = TaxiTracker.wsgi:application

# виртуальное окружение
home = /Users/vladimirkorneev/Desktop/TaxiTracker/TaxiTracker/TaxiTracker/venv

# master процесс
master = true

# процессы
processes = 2

# сокет для nginx
socket = 127.0.0.1:8001

# чистка временных файлов
vacuum = true

# чтобы видеть ошибки
die-on-term = true